apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  selector:
    matchLabels:
      app: db
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: quay.io/sssanikhani/mysql:8
        name: db
        env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "sajjad1234reza1234"
        - name: "MYSQL_DATABASE"
          value: "bolbolestan"
        resources:
          limits:
            memory: "500M"
            cpu: "333m"
          requests:
            memory: "500M"
            cpu: "333m"
        ports:
        - containerPort: 3306
          name: db
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-persistent-storage
            subPath: backend-mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
