apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: sajjad-reza-ns
spec:
  resources:
    requests:
      storage: 2000M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
